workflows:
  golden-test:
    name: Golden Test
    instance_type: mac_mini
    max_build_duration: 75
    environment:
      flutter: stable
    working_directory: packages/golden_tests
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Test
        script: |
          flutter test --update-goldens
          # Upload results of failed Golden tests if test command failed.
          if [ $? -ne 0 ]; then
            # Finds all "failures" folders and copies them to the export
            # directory. Therefore, we are able to view the results of the
            # failed Golden tests.
            #
            # The command will use the exit code 0 (success) even when there are
            # no failures folders.
            find * -path '**/test' -execdir bash -c "cp -r test $FCI_EXPORT_DIR" \;

            # Because we caught the exit code of the test command, we need to
            # set manually again.
            exit 1
          fi
