workflows:
  golden-test:
    name: Golden Test
    instance_type: mac_mini
    max_build_duration: 75
    environment:
      flutter: stable
    working_directory: packages/golden_tests
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Test
        script: |
          flutter test --update-goldens
          cp -r test $FCI_EXPORT_DIR
